- name: install mysql
  hosts: mysql
  become: yes
  tasks:
    - name : install complete mysql
      ansible.builtin.package:
         name : mysql-server
         state: present

    - name: Start service mysqld, if not started
      ansible.builtin.service:
         name: mysqld
         state: started

    - name: excute command
      ansible.builtin.shell: ps aux | grep mysql | grep -v grep  
      register: command_output
      ignore_errors: true

      - name: excute command
      ansible.builtin.shell: ps aux | grep mysql | grep -v grep  
      register: command_output
      ignore_errors: true

    - name: excute command
      ansible.builtin.command: mysql_secure_installation --set-root-pass ExpenseApp@1 
      when: command_output.failed == true
