- name: install mysql
  hosts: mysql
  become: yes
  tasks:
    - name : install complete mysql
      ansible.builtin.package:
         name : mysql-server
         state: present

    - name: Start service mysqld, if not started
      ansible.builtin.service:
         name: mysqld
         state: started

    - name: check mysql connectivty
      ansible.builtin.shell: ps aux | grep mysql | grep -v grep  
      register: command_output
      ignore_errors: true

    - name: Get MySQL version with non-default credentials
      community.mysql.mysql_info:
         login_user: root
         login_password: "{{ mysql_root_password }}"
         login_host: mysql
       register: result
       ignore_errors: true

    - name: excute command
      ansible.builtin.command: mysql_secure_installation --set-root-pass ExpenseApp@1 
      when: result.failed == true
