- name: install mysql
  hosts: mysql
  tasks:
   - name : install complete mysql
     ansible.builtin.package:
         name : mysql-server
         state: present

  - name: Start service mysqld, if not started
     ansible.builtin.service:
        name: mysqld
        state: started

  # - name: excute command
  #    ansible.builtin.command: mysql -h db.aws82s.online -u root -pExpenseApp@1 
  #    register: command_output

  # - name: excute command
  #    ansible.builtin.command: mysql_secure_installation --set-root-pass ExpenseApp@1 
  #    when:command_output.rc != 0
