- name: excute command
  hosts: mysql
  tasks:
    - name : connect mysql
      ansible.builtin.shell: ps aux | grep mysql | grep -v grep 
      register: command_output
      meta: end_play
      ignore_errors: true