- name: excute command
  hosts: mysql
  tasks:
    - name : connect mysql
      ansible.builtin.command: mysql -h db.aws82s.online -u root -pExpenseApp@1 
      register: command_output
      meta: end_play
      ignore_errors: true