- name: variables
  hosts: mysql
  vars:
     name: manju
     age: 120
  tasks:
  - name: Display all variables/facts known for a host
    ansible.builtin.debug:
      msg: " manju: {{ name }}, age: {{ age }}"